allow templatename override

diff --git a/check-deploy b/check-deploy
--- a/check-deploy
+++ b/check-deploy
@@ -9,24 +9,26 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" #this directory
 [[ -f "/home/dokku/dokku-path-routing/ENV" ]] && source "/home/dokku/dokku-path-routing/ENV"
 [[ -f "$DOKKU_ROOT/$APP/ENV" ]] && source $DOKKU_ROOT/$APP/ENV
 # echo "DOKKU_CHECKS_WAIT is $DOKKU_CHECKS_WAIT"
-FILENAME="$DOKKU_ROOT/$APP/dokku-path-routing.conf"
+
+DOKKU_PATH_TEMPLATE_NAME=${DOKKU_PATH_TEMPLATE_NAME:-dokku-path-routing.conf}
+FILENAME="$DOKKU_ROOT/$APP/$DOKKU_PATH_TEMPLATE_NAME"
 
 TMPDIR=$(mktemp -d /tmp/PATHROUTING.XXXXX)
 # choose the template and copy the template to a temp directory
 if [[ ! -f "$FILENAME" ]] ; then
     echo "       path-routing: $FILENAME not found. attempting to retrieve it from container ..."
-    docker cp $CONTAINERID:/app/dokku-path-routing.conf $TMPDIR 2> /dev/null || true
-    if [[ ! -s "${TMPDIR}/PATHROUTING" ]] ; then
-        echo "       dokku-path-routing.conf file not found in container. applying default."
-        cp $DIR/dokku-path-routing.conf $TMPDIR
+    docker cp $CONTAINERID:/app/$DOKKU_PATH_TEMPLATE_NAME $TMPDIR 2> /dev/null || true
+    if [[ ! -s "${TMPDIR}/$DOKKU_PATH_TEMPLATE_NAME" ]] ; then
+        echo "       $DOKKU_PATH_TEMPLATE_NAME file not found in container. applying default."
+        cp $DIR/$NAME $TMPDIR
     else
-        echo "       dokku-path-routing.conf file found in container"
+        echo "       $DOKKU_PATH_TEMPLATE_NAME file found in container"
     fi
 else
     cp $FILENAME $TMPDIR
 fi
 
-FILENAME=$TMPDIR/dokku-path-routing.conf
+FILENAME=$TMPDIR/$DOKKU_PATH_TEMPLATE_NAME
 
 function cleanup() {
   echo "       removing dokku-path-routing file copied from container"
